# Generated by Django 2.2.3 on 2019-10-18 01:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(choices=[('terreo', 'terreo'), ('1 andar', '1 andar')], default='terreo', max_length=255)),
                ('sala', models.CharField(choices=[('terreo', 'terreo'), ('1 andar', '1 andar')], default='LAB 03', max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('tipo_recurso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TipoLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(choices=[('professor', 'professor'), ('laboratorista', 'laboratorista')], default='professor', max_length=255),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_chegada', models.DateTimeField(blank=True, null=True)),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('justificativa', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmacao', models.BooleanField(blank=True, null=True)),
                ('tipo_recurso', models.CharField(blank=True, max_length=255, null=True)),
                ('disciplina', models.CharField(blank=True, max_length=255, null=True)),
                ('curso', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_professor', models.CharField(blank=True, max_length=255, null=True)),
                ('turno', models.CharField(blank=True, max_length=255, null=True)),
                ('primeira_aula', models.BooleanField(blank=True, null=True)),
                ('segunda_aula', models.BooleanField(blank=True, null=True)),
                ('id_recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authweb.Recurso')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authweb.Usuario')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authweb.Situacao')),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='recurso',
            name='tipo_laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authweb.TipoLaboratorio'),
        ),
    ]
