# Generated by Django 2.2.3 on 2019-10-23 00:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authweb', '0002_auto_20191017_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='undefined', max_length=14),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='localizacao',
            field=models.CharField(blank=True, choices=[('terreo', 'terreo'), ('1 andar', '1 andar')], default='terreo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='sala',
            field=models.CharField(blank=True, choices=[('LAB 03', 'LAB 03'), ('LAB 04', 'LAB 04'), ('LAB 05', 'LAB 05'), ('LAB 06', 'LAB 06'), ('LAB 07', 'LAB 07'), ('LAB 08', 'LAB 08'), ('LAB 09', 'LAB 09'), ('LAB 10', 'LAB 10'), ('LAB 11', 'LAB 11'), ('LAB 13', 'LAB 13'), ('LAB 14', 'LAB 14'), ('LAB 15', 'LAB 15'), ('LAB 16', 'LAB 16'), ('LAB 17', 'LAB 17'), ('LAB 18', 'LAB 18'), ('LAB 19', 'LAB 19'), ('LAB 20', 'LAB 20')], default='LAB 03', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authweb.TipoLaboratorio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='curso',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='authweb.Curso'),
        ),
    ]
